### ISSUE TITLE
MVC structure?

### ISSUE THREAD

**Issue by joenas** [joenas/torrent_search#1]
Might be a good idea with more complex actions. Menu probably shouldn't call actions on it self but on a controller.

**Comment by joenas** [comment]
@mskog what is CLI, a view?

**Comment by joenas** [comment]
~~[Draft](https://github.com/joenas/torrent_search/tree/mvc)~~
[Implemented](https://github.com/joenas/torrent_search/pull/6)

**Comment by mskog** [comment]
Late to the party!
I like to look at CLI as interfaces, much like an API or a web based UI

In this case maybe put all the CLI related stuff in its own directory. The project can become pretty big if you want to implement trackers with login or other cool things.
